
```{r}
DATADIR="~/scailscratch/dox/"
library("dplyr")
library("tidyr")
library(data.table)
source("utils.R")
registerDoMC(7)

genotype=fread("zcat < ../data/genotype.txt.gz", data.table = F, header = T)

rownames(genotype)=genotype$snpid
genotype$snpid=NULL

genotype=as.matrix(genotype)

sample_anno=read.table("../data/annotation.txt", header=T, stringsAsFactors = F)

geneloc=read.table(paste0(DATADIR,"genelocGRCh38.txt"),header=T,stringsAsFactors = F)
snploc=read.table(paste0(DATADIR,"snploc.txt"),header=T,stringsAsFactors = F)

normalization_approach="qq"

stopifnot(all(as.character(snploc$snpid) %in% rownames(genotype) ))
genotype=genotype[as.character(snploc$snpid),]

input <- read.delim("../data/counts_log_cpm.txt.gz")

anno <- read.delim("../data/sample_annotation.txt", stringsAsFactors = F)

sample_anno=read.table("../data/annotation.txt", header=T, stringsAsFactors = F)

# mapping from cell-line ID to individual
findiv=sample_anno$findiv
names(findiv)=sample_anno$cell_line
stopifnot(is.character(anno$individual))

colnames(input)=findiv[anno$individual]

#input=remove_PCs(input, num_PCs_to_remove)
if (normalization_approach=="qq") {
  input=quantile_normalize(input)
} else if (normalization_approach=="log") {
  input=input %>% t %>% scale %>% t
} else if (normalization_approach=="linear") {
  input=(2^input) %>% t %>% scale %>% t
}

findiv[ findiv==160001 ]=106411

anno$findiv=as.character(findiv[anno$individual])
```

```{r}
res_dir="../panama_qq_boot/"
eqtl=foreach(fn=list.files(res_dir,glob2rx("chr*.txt.gz")), .combine = bind_rows) %do% {
  print(fn)
  read.table(paste0(res_dir,fn), header = T, stringsAsFactors = F)
}

df=4
eqtl=eqtl %>% mutate( p_geno=lrt_pvalue(l_geno-l0,df=1),
                      p_interact=lrt_pvalue(l_interact-l_geno,df=df), 
                      p_joint=lrt_pvalue(l_interact-l0,df=df+1),
                      p_boot=lrt_pvalue(l_boot_interact - l_boot_geno, df ) )

interact_bf=eqtl %>% mutate(p=p_interact) %>% bonferroni
```

```{r}
require(rstan)
panama_test=stan_model("panama_test.stan")

genes=intersect(rownames(input),geneloc$geneid)
rownames(geneloc)=geneloc$geneid
cisdist=1e5
errorhandling=if (interactive()) 'stop' else 'remove'

K=readRDS("../data/Kern.rds")
eig_K=eigen(K)

anno = anno %>% mutate(conc=as.factor(conc))
no_geno = model.matrix( ~ conc, data=anno) # [,2:5]

N=ncol(input)

hits = interact_bf %>% filter(q < 0.05) %>% arrange(p)

betas=foreach(i=1:nrow(hits), .errorhandling=errorhandling, .combine = cbind) %dopar% {
  hit=hits[i,]
  gene=hit$gene

  y=input[gene,] %>% as.numeric
  y=y-mean(y)
  
  cis_snps=snploc[ ((geneloc[gene,"left"]-cisdist) < snploc$pos) & ((geneloc[gene,"right"]+cisdist) > snploc$pos), "snpid" ]
  cis_snps=as.character(cis_snps)

  imp_geno=easy_impute(genotype[cis_snps,])
  
  data=list(N=N,U_transpose_x=t(eig_K$vectors) %*% no_geno,P=ncol(no_geno), U_transpose_y=t(eig_K$vectors) %*% y %>% as.numeric, lambda=eig_K$values)

  init=list(sigma2=0.1, sigma2_k=1.0, beta=lm(y ~ no_geno - 1) %>% coef )

  fit_no_geno=optimizing(panama_test, data, init=init, as_vector=F)
  cis_snp=hit$cis_snp %>% as.character()
  
  geno=imp_geno[cis_snp,anno$findiv]

  lrt = function(data) {
    data$U_transpose_x=t(eig_K$vectors) %*% cbind( no_geno, geno )
    data$P=ncol(data$U_transpose_x)
    init=fit_no_geno$par
    init$beta=c(init$beta,0.0)
    
    fit_geno=optimizing(panama_test, data, init=init, as_vector=F )
    
    interact=model.matrix(~geno:conc,data=anno)
    interact=interact[,3:ncol(interact)]
    data_interact=data
    data_interact$U_transpose_x=t(eig_K$vectors) %*% cbind( no_geno, geno, interact )
    data_interact$P=ncol(data_interact$U_transpose_x)
  
    init=fit_geno$par
    init$beta=c(init$beta,numeric(ncol(interact)))
    fit_interact=optimizing(panama_test, data_interact, init=init, as_vector=F)
    
    list( fit_geno=fit_geno, fit_interact=fit_interact )
  }
    
  lrt( data )$fit_interact$par$beta
} %>% t

saveRDS(betas, file="../data/sig_betas.rds")"
```

```{r}
mix_model=stan_model("mix.stan")

data=list(y=betas, K=20, P=ncol(betas), N=nrow(betas))
os=foreach(i=1:7) %dopar% { optimizing(mix_model, data=data, as_vector=F) }
foreach(o=os, .combine = c) %do% { o$value }
normalize_rows=function(g) sweep(g,1,rowSums(g),"/")
logl=foreach(o=os, .combine = c) %do% { o$value }
foreach(o=os, .combine = c) %do% { o$par$logprob %>% exp %>% normalize_rows() %>% apply(1,which.max) %>% unique() %>% length() }
o=os[[ which.max(logl) ]]
assignments = o$par$logprob %>% exp %>% normalize_rows() %>% apply(1,which.max)
used=assignments %>% unique()
use_counts=assignments %>% table()

foreach(i=used) %do% {
  x=cbind( no_geno, geno, interact )
  data.frame(y=(x %*% o$par$means[i,]) %>% as.numeric(), geno=as.factor(geno), conc=anno$conc) %>% filter(!is.na(geno)) %>% ggplot(aes(as.factor(conc), y, col=geno)) + geom_boxplot() + ggtitle(paste("Cluster:",i," (",use_counts[as.character(i)],")")) + ylab("Expression") + xlab("Dox concentration") + theme_bw(base_size=16) 
}
```