---
title: "Expression patterns"
output:
  html_document:
    fig_width: 6
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(doMC)
registerDoMC(detectCores()-1)
```

## Load expression data
```{r}
DATADIR="~/scailscratch/dox/"
library("dplyr")
library(data.table)
source("utils.R")

sample_anno=read.table("../data/annotation.txt", header=T, stringsAsFactors = F)
errorCovariance=get_relatedness("../data/addSNP.coef.3671", unique(sample_anno$findiv))

input <- read.delim("../data/counts_log_cpm.txt.gz")

anno <- read.delim("../data/sample_annotation.txt", stringsAsFactors = F)

sample_anno=read.table("../data/annotation.txt", header=T, stringsAsFactors = F)

# mapping from cell-line ID to individual
findiv=sample_anno$findiv
names(findiv)=sample_anno$cell_line
stopifnot(is.character(anno$individual))

colnames(input)=findiv[anno$individual]

#input=remove_PCs(input, num_PCs_to_remove)
input=quantile_normalize(input)
```

## Run basic DE analysis

```{r}
anno$findiv=as.character(findiv[anno$individual])
genes=rownames(input)
pvalues=setNames( foreach(gene=genes, .errorhandling='pass', .combine = c) %dopar% {
  y=input[gene,]
  anova( lm(y ~ as.factor(anno$conc)), lm(y ~ 1))["Pr(>F)"][2,1]
}, genes )
qplot(pvalues, geom="blank") + geom_histogram() + theme_bw(base_size = 16) + xlab("p-value")
ggsave("../figures/de_boring.pdf", width = 5, heigh=5)
q=p.adjust(pvalues,method="BH")
mean(q<.05) # 98% DE! 
```

## Expression pattern analysis
```{r}
require(rstan)

dim(input)
y=t(scale(t(input)))
x=model.matrix(~as.factor(conc)-1, data=anno)
#x=x[,2:ncol(x)]
data=list(y=y, N=ncol(y), D=nrow(y), x=x, P=ncol(x), K=20)

cached_fit_fn="../data/expression_patterns.RData"
if (F) {
  mixlm_model=stan_model("mixlm_pred.stan")
  mixlm_fit=optimizing(mixlm_model, data, verbose=T, iter=100,  as_vector=F) # takes a while... 
  save(file=cached_fit_fn, mixlm_fit)
} else {
  load(cached_fit_fn)
}
ggplot( data.frame(n=1:20, p=sort(mixlm_fit$par$p, decreasing = T)), aes(n,p)) + geom_bar(stat="identity") + theme_bw(base_size = 16) + ylab("Mixture weight") + xlab("Mixture component")
```

Take top six clusters
```{r}
to_use=order(mixlm_fit$par$p, decreasing = T)[1:6]
mix_means=mixlm_fit$par$betas[to_use,]

assignments=apply(mixlm_fit$par$logprob, 1, which.max)
# save(file="../data/expression_patterns.RData", mixlm_fit, assignments)

plot(table(assignments))
```

Plot expression patterns
```{r}
concs=sort(unique(anno$conc))
colnames(mix_means)=concs

require(reshape2)
m=melt(mix_means, value.name="mean")
colnames(m)=c("mixture","conc","mean")
weights=mixlm_fit$par$p[to_use]
m$pi=weights[m$mixture]
m$mixture=as.factor(m$mixture)
ggplot(m, aes(conc, mean, col=mixture, shape=mixture, size=pi)) + geom_line(alpha=.5) + geom_point() + scale_x_sqrt() + theme_bw(base_size = 16) + ylab("Relative expression") + xlab("Dox concentration")
```

1. Down regulated
2. Initial increase, then decrease
3. Up regulated
4. Transient down regulation
5. Transient up regulation
6. Down regulation and then some recovery. 


```{r}
source("GOtest.R")

to_use=order(mixlm_fit$par$p, decreasing = T)[1:6]
mix_means=mixlm_fit$par$betas[to_use,]

assignments=apply(mixlm_fit$par$logprob[,to_use], 1, which.max)

GO_res=foreach(i=1:6) %do% {
  summary(GOtest(rownames(y), rownames(y)[assignments==i], ontology = "BP")$GO$BP, pvalue = 1e-5)
}

go_data <- goHeatmapData(GO_res)

go_heatmap <- plotHeatmap(go_data, labCol = "")

```