---
title: "Compare to GTEx heart_all eQTL"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(data.table)
require(ggplot2)
theme_set(theme_bw(base_size = 14))
```

```{r}
source("load_gtex_eqtl.R")
```

```{r}
eqtl = fread("zcat < ../data/panana_all_eqtl.txt.gz", data.table = F)
```

```{r}
source("../code/utils.R")
geno_bf=eqtl %>% mutate(p=p_geno) %>% bonferroni
geno_threshold=geno_bf %>% filter(q<.05) %>% .$p %>% max
geno_threshold
sum(geno_bf$q < 0.05) # 202, 674
```

Nominal p of 1e-5 is roughly cutoff for nomimal FDR 0.05. 
```{r}
require(qvalue)
geno_threshold=1e-5
replication_rates = foreach(tis_n=names(gtex_tis), .combine = bind_rows) %dopar% {
  tis=gtex_tis[[tis_n]]
  eqtl_join_gtex = eqtl %>% inner_join(tis, by=c(gene="gene_id", RSID="RSID"))

  rep_p = eqtl_join_gtex %>% filter(p_geno < geno_threshold) %>% .$pval_nominal
  
  data.frame( tissue=tis_n, prop_shared=nrow(eqtl_join_gtex)/nrow(eqtl), naive_rep= mean(rep_p < 0.05), p1= 1. - pi0est(rep_p)$pi0, stringsAsFactors = F)
}
replication_rates %>% mutate(tissue=factor(tissue,c("brain","lcl","heart"),c("Brain (Cerebellum)","Lymphoblastoid cell line","Heart (Left Ventricle)"))) %>% ggplot(aes(tissue, p1)) + geom_bar(stat='identity') + xlab("GTEx tissue") + ylab("Storey's pi1") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + ylim(0,1)
ggsave("../figures/gtex.pdf",width=3,height=4)
```


```{r}
eqtl_join_gtex = eqtl %>% inner_join(gtex_tis$heart, by=c(gene="gene_id", RSID="RSID"))
bonferroni_with_gtex=function(g) { g %>% group_by(gene) %>% 
    summarize( cis_snp=cis_snp[which.min(p)], p=min(p) * length(p), gtex_p=pval_nominal[which.min(p)]  ) %>% 
    mutate( q=p %>% pmin(1) %>% p.adjust(method="BH") ) }
geno_at_gtex=eqtl_join_gtex %>% mutate(p=p_geno) %>% bonferroni_with_gtex
gtex_p_at_sig=geno_at_gtex %>% filter(q<0.05) %>% .$gtex_p
mean( gtex_p_at_sig< 0.05 )
hist(gtex_p_at_sig,100)
1-qvalue(gtex_p_at_sig)$pi0
```

```{r}
gtex_p1= read.table("../data/gtex_p1.txt.gz", header=T, stringsAsFactors = F) %>% mutate(tissue=str_split_fixed(gtex_file, "/", 9)[,9], tissue= str_split_fixed(tissue, pattern="[.]", n=4)[,1]) %>% select(-gtex_file)
gtex_p1 %>% group_by(geno_threshold,eqtls) %>% arrange(p1) %>% summarise(rank=mean(c(which(tissue=="Heart_Left_Ventricle"), which(tissue=="Heart_Atrial_Appendage")))) %>% ungroup() %>% arrange(geno_threshold)
gtex_p1 %>% group_by(geno_threshold,eqtls) %>% arrange(p1) %>% summarise(rank=which(tissue=="Heart_Atrial_Appendage")) %>% ungroup() %>% arrange(geno_threshold)
# Heart_Left_Ventricle
gtex_p1 %>% group_by(geno_threshold,eqtls) %>% arrange(p1) %>% summarise(rank=which(tissue=="Muscle_Skeletal")) %>% ungroup() %>% arrange(geno_threshold)
```


```{r}
geno_thres=5e-05
tissue_order=gtex_p1 %>% filter(geno_threshold==geno_thres,eqtls=="my_eqtl") %>% arrange(p1) %>% .$tissue
gtex_p1 %>% filter(geno_threshold==geno_thres) %>% mutate(tissue=factor(tissue, tissue_order)) %>% ggplot(aes(tissue, p1, fill=eqtls)) + geom_bar(stat="identity", position="dodge") + coord_flip()
```

```{r}
subset=c("Vagina", "Uterus", "Brain_Amygdala", "Brain_Hypothalamus", "Ovary", "Liver", "Prostate", "Spleen", "Artery_Coronary", "Breast_Mammary_Tissue", "Testis", "Whole_Blood", "Colon", "Pancreas", "Stomach", "Brain_Cerebellum", "Muscle_Skeletal", "Lung", "Heart_Left_Ventricle", "Heart_Atrial_Appendage", "Cells_EBV-transformed_lymphocytes")
labels=tissue_order
labels[labels=="Cells_EBV-transformed_lymphocytes"]="LCL"
labels=gsub("_"," ",labels)
labels=gsub(" Tissue","",labels)
gtex_p1 %>% filter(geno_threshold==geno_thres, tissue %in% subset, eqtls=="my_eqtl")  %>% mutate(tissue=factor(tissue, tissue_order,labels = labels)) %>% ggplot(aes(tissue, p1)) + geom_bar(stat="identity", position="dodge") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + ylab("Storey's pi1") + xlab(NULL) + ylim(0,1) + coord_flip()
ggsave("../figures/gtex_rep.pdf", width=3.5, height=3.5)
```

