---
title: "Cardiac troponin measurements"
date: 2016-10-04
output:
  html_document:
    toc: true
    toc_float: true
---

```{r}
require(rstan)
library(tidyverse)
require(dplyr)
require(magrittr)
require(ggplot2)
require(glmnet)
require(doMC)
registerDoMC(7)

source("../code/utils.R")

source("../code/load_data.R")

pred_exp = fread(paste0("zcat < ",DATADIR,"predicted_log_cpm.txt.gz"), sep="\t", data.table=F)
rownames(pred_exp)=pred_exp$V1
pred_exp$V1=NULL
pred_exp=as.matrix(pred_exp)
```

```{r}
is_predictable=foreach(i=1:nrow(pred_exp), .combine = c) %dopar% {
  x=pred_exp[i,] %>% as.matrix() %>% as.numeric()
  y=input[rownames(pred_exp)[i],] %>% as.matrix() %>% as.numeric()
  anova( lm(y ~ x + factor(anno$conc)), lm(y ~ factor(anno$conc)) )$`Pr(>F)`[2]
}

is_predictable_q=p.adjust(is_predictable, method="BH")

pred_exp = pred_exp[is_predictable_q < 0.01, ]
```

```{r}
pca <- prcomp(t(pred_exp), scale. = TRUE)
variances <- pca$sdev^2
explained <- variances / sum(variances)

pca_data <- cbind(anno, pca$x[, 1:5])

pca_data %>% mutate(conc=as.factor(conc)) %>% 
  ggplot( aes(x = PC1, y = PC2, group=individual, color=conc)) +
  geom_text(aes(label = conc)) +
  geom_path(alpha=.3) +
  labs(x = sprintf("PC%d (%.2f%%)", 1, round(explained[1] * 100, 2)),
       y = sprintf("PC%d (%.2f%%)", 2, round(explained[2] * 100, 2)))
```

Normalizing across all concs looks cleanest. Fit principal curve: 
```{r}
require(princurve)
pca_data_to_use=pca_data
cols=paste0("PC",1:2)
start = pca_data_to_use %>% group_by(conc) %>% select(PC1,PC2) %>% summarise_all(mean) %>% ungroup() %>% select(PC1,PC2) %>% as.matrix()
pcurve=principal.curve(pca_data_to_use[,cols] %>% as.matrix, start=start)
pca_data$lambda=pcurve$lambda
curve_df=data.frame(x=pcurve$s[pcurve$tag,1],y=pcurve$s[pcurve$tag,2])
pca_df=pca_data_to_use %>% mutate(conc=as.factor(conc))
projection_df=data.frame(conc=pca_df$conc, x=pca_df$PC1, y=pca_df$PC2, xend=pcurve$s[,1], yend=pcurve$s[,2])
ggplot(curve_df, aes(x,y)) + geom_point( data=pca_df, aes(x = PC1, y = PC2, color=conc)) + geom_segment(data=projection_df, aes(x=x,y=y,xend=xend,yend=yend,col=conc))+ geom_path() +
  labs(x = sprintf("PC%d (%.2f%%)", 1, round(explained[1] * 100, 2)),
       y = sprintf("PC%d (%.2f%%)", 2, round(explained[2] * 100, 2))) + theme(legend.position = c(.8,.2)) + scale_color_manual(values=cbPalette)
#ggsave("../figures/prin_curve.pdf",height = 4,width=4.5,device=cairo_pdf)
```

```{r}
pca_data %>% ggplot(aes(conc %>% as.factor() %>% as.numeric(), lambda / max(lambda), group=individual, col=individual)) + geom_point() + geom_path() + xlab("Dox concenration") + scale_x_continuous(breaks=1:5, labels = unique(pca_data$conc)) + ylab("Position on principal curve")
```

### Initial progression rate

```{r}
require(broom)
progression_rate = pca_data %>% filter(conc %in% c(0.,.625,1.25)) %>% group_by(individual) %>% do(tidy(lm(lambda ~ conc - 1, data=.))) %>% filter(!is.na(estimate), term=="conc" )
hist(progression_rate$estimate)
```

```{r}
require(scales) # trans_new() is in the scales library
asinh_trans = function() trans_new("asinh", asinh, sinh)

progression_rate$dbgap=dbgap[ progression_rate$individual ]

joined = progression_rate %>% 
  left_join(troponin_rate %>% mutate(individual=individual %>% as.character()), by=c(dbgap="individual")) 

cor.test(joined$estimate, joined$intercepts)
cor.test(joined$estimate, joined$slopes)
cor.test(joined$estimate, joined$slopes, method="spearman")

#joined %>% ggplot(aes(estimate, intercepts)) + geom_point() # not significant
joined %>% ggplot(aes(estimate, slopes, label=individual)) + geom_point(alpha=0.1) + geom_text() + xlab("Transcriptomic response") + ylab("Troponin response") +stat_smooth(method="lm", fullrange = T) + coord_trans(y = "asinh", x="log")
#ggsave("../figures/troponin_vs_transcriptome.pdf",height = 4,width=4,device=cairo_pdf)
```


```{r}
troponin_df=read.table("../data/troponin-processed.txt", header=T, stringsAsFactors = F)
troponin_df
anno = anno %>% left_join(troponin_df %>% select(dbgap, dosage, troponin), by=c("dbgap"="dbgap", "conc"="dosage"))
```

```{r}
de=foreach(conc=concs) %do% {
  print(conc)
  to_use=anno$conc==conc
  trop=anno$troponin[to_use]
  suppressWarnings(
  { one_conc =  foreach(i=1:nrow(pred_exp), .combine = bind_rows) %dopar% {
    ct = cor.test(pred_exp[i,to_use] %>% as.numeric(),trop,method="spearman")
    data.frame(p=ct$p.value, rho=ct$estimate)
  } } )
  one_conc %>% mutate(p_adjust=p.adjust(p, method="BH"), q=qvalue(p)$qvalues)
} %>% set_names(concs)
```


```{r}
foreach(p=de, .combine = c) %do% { sum(p$p_adjust<0.1) }
foreach(p=de, .combine = c) %do% { sum(p$q<0.1) }
pi0s = foreach(p=de, .combine = c) %do% { 1. - pi0est(p$p)$pi0 }
qplot(concs,pi0s)
```

```{r}
#gz=gzfile("../supp_data/troponin_differential_genes.txt.gz", "w")
top_res=foreach(conc=as.character(concs), .combine = bind_rows) %do% { de[[conc]] %>% mutate(conc=conc, gene=rownames(pred_exp)) %>% filter(q < 0.1) %>% select(conc, gene, rho, p, q) } # %>% write.table( gz, quote=F, row.names = F, col.names=T, sep="\t")
ta=table(top_res$gene)
top_res %>% filter(gene %in% names(ta[ta>1]))
# close(gz)
```

```{r}
ensg_to_hugo=fread("zcat < ../data/ensg_to_hugo.txt.gz", data.table = F) %>% 
  set_colnames(c("hugo","ensembl"))
ensg_to_hugo_no_trop = ensg_to_hugo %>% filter(!grepl("TNNT",hugo),!grepl("TNNI",hugo))
shared_genes=intersect(rownames(pred_exp),ensg_to_hugo_no_trop$ensembl)
ge_no_trop=pred_exp[shared_genes,]
dim(ge_no_trop)
```
```{r}
anno=anno %>% group_by(conc) %>% mutate(trop_normed=scale(troponin)) %>% ungroup()
input_normalized = t(ge_no_trop) %>% scale()
cv=cv.glmnet(input_normalized, anno$trop_normed, nfolds=nrow(anno), parallel=T, keep=T)
#1. - var(anno$trop_normed - cv$fit.preval[,which.min(cv$cvm)]) / var(anno$trop_normed)
co = coef(cv, s="lambda.min")
fitt = cbind(1,input_normalized) %*% co %>% as.numeric()
1. - var(fitt - as.numeric(anno$trop_normed)) / var( as.numeric(anno$trop_normed) ) # 89%
```


```{r, message=F, warning=F}
gcat_stan=stan_model("gcat.stan")

prep_data=function(ge, y) {
  y = scale(y)
  ge = scale(ge)
  gram_matrix=ge %*% t(ge) / ncol(ge)
  eigen_sample_kernel=eigen(gram_matrix)
  list(N=length(y), U_transpose_y=t(eigen_sample_kernel$vectors) %*% y %>% as.numeric, lambda=eigen_sample_kernel$values)
}
```

```{r}
dat=prep_data(t(ge_no_trop), as.numeric(anno$trop_normed))
o=optimizing(gcat_stan, data=dat, init=0, as_vector=F)
o$par %>% as.data.frame() %>% mutate(pve=sigma2_k / (sigma2_k + sigma2)) # 2.360128 0.1175105 0.9525716
```

```{r}
samples=sampling(gcat_stan, data=dat, show_messages=F, verbose=F, refresh=0) %>% rstan::extract(c("sigma2_k","sigma2")) %>% as.data.frame() %>% mutate(pve=sigma2_k / (sigma2_k + sigma2))
quantile(samples$pve, c(0.025,.975) ) # 0.8899447 0.9915149
```
